baseURL = "https://erwandupas.com/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Erwan Dupas"
theme = "blowfish"

[languages]

  [languages.fr]
    languageName = "Français"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2

[params]
colorScheme = "blowfish"
defaultBackgroundImage = "background.jpg"

[params.author]
name = "Erwan Dupas"
image = "me.jpg"
headline = "Créateur de contenus"
bio = "Bienvenue sur mon Hub numérique.Ici, je centralise mes contenus :)"

[params.author.links]
  [[params.author.links.linkedin]]
    href = "https://www.linkedin.com/in/erwan-dupas/"

  [[params.author.links.youtube]]
    href = "https://youtube.com/@toncompte"

  [[params.author.links.email]]
    href = "mailto:eddy404@pm.me"

[params.homepage]
layout = "profile"
showRecent = true
recentLimit = 3
