baseURL = "https://erwandupas.com/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Erwan Dupas"
theme = "blowfish"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1

[params]
colorScheme = "blowfish"
defaultBackgroundImage = "background.jpg"

[params.author]
name = "Erwan Dupas"
image = "me.jpg"
headline = "Créateur de contenus"
bio = "Bienvenue sur mon Hub numérique.Ici, je centralise mes contenus :)"

[params.author.links]
linkedin = "https://www.linkedin.com/in/erwan-dupas/"
youtube = "https://youtube.com/@toncompte"
email = "mailto:eddy404@pm.me"

[params.homepage]
layout = "profile"
showRecent = true
recentLimit = 3
